-- Part 2: Helper functions needed by tables

CREATE OR REPLACE FUNCTION "public"."requesting_user_id"() RETURNS "text"
    LANGUAGE "sql" STABLE
    AS $$
  select nullif(current_setting('request.jwt.claims', true)::json->>'sub', '')::text;
$$;

-- Core tables

CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" "text" DEFAULT "public"."requesting_user_id"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "displayName" "text",
    CONSTRAINT "Users_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."Podcasts" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "url" "text",
    "rssUrl" "text",
    "imageUrl" "text",
    "owner" "text" DEFAULT "public"."requesting_user_id"(),
    "copyright" "text",
    "author" "text",
    "private" boolean DEFAULT true,
    "uuid" "uuid" DEFAULT "gen_random_uuid"(),
    "published" boolean DEFAULT false,
    "process" boolean DEFAULT false NOT NULL,
    CONSTRAINT "Podcasts_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Podcasts_unique_id_and_slug" UNIQUE ("id", "slug")
);

CREATE TABLE IF NOT EXISTS "public"."Episodes" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "podcast" bigint NOT NULL,
    "slug" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "url" "text",
    "imageUrl" "text",
    "audioUrl" "text",
    "transcriptUrl" "text",
    "summaryUrl" "text",
    "pubDate" timestamp with time zone,
    "guid" "text",
    "error" "jsonb",
    "rawTranscriptUrl" "text",
    "modified_at" timestamp with time zone DEFAULT "now"(),
    "status" "jsonb",
    "originalAudioUrl" "text",
    "published" boolean DEFAULT false,
    "duration" bigint,
    CONSTRAINT "Episodes_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Episodes_unique_guid" UNIQUE ("guid"),
    CONSTRAINT "Episodes_unique_id_and_guid" UNIQUE ("id", "guid")
);

CREATE TABLE IF NOT EXISTS "public"."Documents" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "checksum" "text",
    "meta" "jsonb",
    "episode" bigint,
    "source" "text",
    "created_at" timestamp with time zone,
    CONSTRAINT "nods_page_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uniquedocumentsourceurl" UNIQUE ("episode", "source")
);

CREATE TABLE IF NOT EXISTS "public"."Chunks" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "document" bigint NOT NULL,
    "content" "text",
    "embedding" "public"."vector"(768),
    "meta" "jsonb",
    CONSTRAINT "nods_page_section_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."SpeakerMap" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "speakerId" "text" NOT NULL,
    "name" "text",
    "episode" bigint NOT NULL,
    "modified_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "SpeakerMap_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uniquespeakermapping" UNIQUE ("speakerId", "episode")
);

CREATE TABLE IF NOT EXISTS "public"."Subscriptions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user" "text" NOT NULL,
    "description" "text",
    "state" "text" NOT NULL,
    "plan" "text" NOT NULL,
    "billingProviderId" "text",
    "modified_at" timestamp with time zone DEFAULT "now"(),
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone,
    CONSTRAINT "Subscriptions_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."Suggestions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "episode" bigint,
    "suggestion" "text",
    "podcast" bigint,
    CONSTRAINT "Suggestions_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."Invitations" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "modified_at" timestamp with time zone DEFAULT "now"(),
    "podcast" bigint NOT NULL,
    "name" "text",
    "email" "text" NOT NULL,
    "status" "text",
    CONSTRAINT "Invitations_pkey" PRIMARY KEY ("id")
);

-- Foreign keys
ALTER TABLE ONLY "public"."Episodes"
    ADD CONSTRAINT "Episodes_podcast_fkey" FOREIGN KEY ("podcast") REFERENCES "public"."Podcasts"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Documents"
    ADD CONSTRAINT "public_Documents_episode_fkey" FOREIGN KEY ("episode") REFERENCES "public"."Episodes"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Chunks"
    ADD CONSTRAINT "public_Chunks_document_fkey" FOREIGN KEY ("document") REFERENCES "public"."Documents"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."SpeakerMap"
    ADD CONSTRAINT "SpeakerMap_episode_fkey" FOREIGN KEY ("episode") REFERENCES "public"."Episodes"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Invitations"
    ADD CONSTRAINT "Invitations_podcast_fkey" FOREIGN KEY ("podcast") REFERENCES "public"."Podcasts"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Podcasts"
    ADD CONSTRAINT "public_Podcasts_owner_fkey" FOREIGN KEY ("owner") REFERENCES "public"."Users"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."Subscriptions"
    ADD CONSTRAINT "public_Subscriptions_user_fkey" FOREIGN KEY ("user") REFERENCES "public"."Users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Suggestions"
    ADD CONSTRAINT "Suggestions_podcast_fkey" FOREIGN KEY ("podcast") REFERENCES "public"."Podcasts"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."Suggestions"
    ADD CONSTRAINT "public_Suggestions_episode_fkey" FOREIGN KEY ("episode") REFERENCES "public"."Episodes"("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- Indexes
CREATE INDEX IF NOT EXISTS "Chunks_document_idx" ON "public"."Chunks" USING "hash" ("document");
CREATE INDEX IF NOT EXISTS "Documents_episode_idx" ON "public"."Documents" USING "hash" ("episode");
CREATE INDEX IF NOT EXISTS "Podcasts_owner_idx" ON "public"."Podcasts" USING "hash" ("owner");
CREATE INDEX IF NOT EXISTS "SpeakerMap_episode_idx" ON "public"."SpeakerMap" USING "hash" ("episode");
CREATE INDEX IF NOT EXISTS "Suggestions_episode_idx" ON "public"."Suggestions" USING "hash" ("episode");

-- Categories table
CREATE TABLE IF NOT EXISTS "Categories" (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text,
    "imageUrl" text,
    "displayOrder" integer DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "PodcastCategories" (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    podcast bigint REFERENCES "Podcasts"(id) ON DELETE CASCADE,
    category bigint REFERENCES "Categories"(id) ON DELETE CASCADE,
    UNIQUE (podcast, category)
);

-- Topics table
CREATE TABLE IF NOT EXISTS "Topics" (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    description text,
    embedding vector(768),
    created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "EpisodeTopics" (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    episode bigint REFERENCES "Episodes"(id) ON DELETE CASCADE,
    topic bigint REFERENCES "Topics"(id) ON DELETE CASCADE,
    confidence double precision DEFAULT 1.0,
    UNIQUE (episode, topic)
);

-- Seed categories
INSERT INTO "Categories" (name, slug, description, "displayOrder") VALUES
    ('Technology', 'technology', 'Podcasts about tech, AI, software, and the digital world', 1),
    ('Health', 'health', 'Podcasts about health, wellness, fitness, and mental well-being', 2),
    ('Business', 'business', 'Podcasts about business, startups, investing, and entrepreneurship', 3)
ON CONFLICT (slug) DO NOTHING;
