-- Categories for organizing podcasts
CREATE TABLE IF NOT EXISTS "Categories" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  "imageUrl" text,
  "displayOrder" integer DEFAULT 0
);

-- Join table for podcast-category relationships
CREATE TABLE IF NOT EXISTS "PodcastCategories" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  podcast bigint REFERENCES "Podcasts"(id) ON DELETE CASCADE,
  category bigint REFERENCES "Categories"(id) ON DELETE CASCADE,
  UNIQUE (podcast, category)
);

-- Enable RLS
ALTER TABLE "Categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PodcastCategories" ENABLE ROW LEVEL SECURITY;

-- Read access for all users
CREATE POLICY "Categories are viewable by everyone" ON "Categories"
  FOR SELECT USING (true);

CREATE POLICY "PodcastCategories are viewable by everyone" ON "PodcastCategories"
  FOR SELECT USING (true);

-- Insert/update for authenticated users
CREATE POLICY "Authenticated users can manage categories" ON "Categories"
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can manage podcast categories" ON "PodcastCategories"
  FOR ALL USING (auth.role() = 'authenticated');

-- Pre-seed categories
INSERT INTO "Categories" (name, slug, description, "displayOrder") VALUES
  ('Technology', 'technology', 'Podcasts about tech, AI, software, and the digital world', 1),
  ('Health', 'health', 'Podcasts about health, wellness, fitness, and mental well-being', 2),
  ('Business', 'business', 'Podcasts about business, startups, investing, and entrepreneurship', 3)
ON CONFLICT (slug) DO NOTHING;
